import Footer from "@/shared/components/Footer";
import type { Metadata } from "next";
import { Instrument_Sans, Merriweather } from "next/font/google"; // ✅ import Instrument Sans
import AOSInitializer from "@/shared/config/axios.config";
import { NavbarOption } from "@/shared/components/NavbarOption";
import "./globals.css";

// ✅ Load Instrument Sans (for general body text)
const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-instrument-sans",
  weight: ["400", "500", "600", "700"],
});

// ✅ Keep Merriweather for serif sections if needed
const merriweather = Merriweather({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Optionia",
  description: "Generated by Optionia",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSans.variable} ${merriweather.variable} font-sans antialiased`}
      >
        <NavbarOption />
        <AOSInitializer />
        {children}
        <Footer />
      </body>
    </html>
  );
}
