import Footer from "@/shared/components/Footer";
import { Navbar } from "@/shared/components/Navbar";
import type { Metadata } from "next";
import { Geist, Inter, Merriweather, Poppins } from "next/font/google";
import "./globals.css";
import AOSInitializer from "@/shared/config/axios.config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: ["400", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const poppins = Poppins({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Optionia",
  description: "Generated by Optionia",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriweather.className} antialiased`}>
        <Navbar />
        <AOSInitializer />
        {children}
        <Footer />
      </body>
    </html>
  );
}
